Algoritmo "Dias de vida 11"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/10/2019
Var
// Seção de Declarações das variáveis 
dataden,anoa,meses,dias:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("informe a data de nascimento e o ano atual")
leia(dataden)
leia(anoa)
meses<-(anoa-dataden)*12
dias<-(meses*30)

Fimalgoritmo