Algoritmo "matematicas 05"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/10/2019
Var
// Seção de Declarações das variáveis 

numero1,quadrado,triplo,raiz2,soma:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("informe um numero")
leia(numero1)
quadrado<-(numero1^2)
triplo<-(numero1^3)
raiz2<-(raizq(numero1))
soma<-(quadrado+triplo)


Fimalgoritmo