Algoritmo "IMC 06"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/10/2019
Var
// Seção de Declarações das variáveis 

p,h,imc:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("informe o peso")
leia(p)
escreva("informe a altura")
leia(h)

IMC<-(p/h^2)
escreva(" o valor do IMC e:",IMC)

Fimalgoritmo