Algoritmo "salario a receber 09"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/10/2019
Var
// Seção de Declarações das variáveis 

salb,impo,salr:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("informe o salario base")
leia(salb)
impo<-(salb*6.5)/100
salr<-(salb-impo)
escreva("o salario a receber e:",salr)


Fimalgoritmo